icons = "awesome5"

[theme] 
name = "slick"
[theme.overrides]
separator = ""
idle_bg = "#111111aa"
idle_fg = "#f3f4f5"
good_bg = "#1DB954"
info_bg = "#1DB954"
info_fg = "#000000"
warning_bg = "#FFAB0F"
alternating_tint_bg = "#00000000"
alternating_tint_fg = "#00000000"


#---------------------------------------

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
marquee = false
on_collapsed_click = "spotify" 

[[block]]
block = "sound"
show_volume_when_muted = false
driver = "pulseaudio"

[[block]]
block = "cpu"
interval = 2

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
ap_format = "{strength}%"
device_format = "{icon}{ap}"